[package]
name = "ccspellcheck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.3"
twox-hash = "1.6.3"
bitvec = "1.0.1"
tempfile = "3.10.1"
